[tool.isort]
profile= "black"
multi_line_output= 3
include_trailing_comma= true
force_grid_wrap= 0
use_parentheses= true
line_length= 119

[tool.black]
line-length = 119
target-version = ['py38']
quiet = 0
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | results
  | venv
)/
'''
