train:
  _target_: torch.utils.data.DataLoader
  batch_size: 6
  shuffle: true
  num_workers: 6
  pin_memory: True

val:
  _target_: torch.utils.data.DataLoader
  batch_size: 6
  shuffle: false
  num_workers: 6
  pin_memory: True

test:
  _target_: torch.utils.data.DataLoader
  batch_size: 6
  shuffle: false
  num_workers: 6
  pin_memory: True
